export type PortfolioCategory = 'Todos' | 'E-commerce' | 'Sistema Web' | 'Sistema' | 'Website';

export const portfolioCategories: PortfolioCategory[] = [
  'Todos',
  'E-commerce',
  'Sistema Web',
  'Sistema',
  'Website',
];

export const portfolioItems = [
  {
    num: '01',
    gradient: 'from-[#1a1a2e] to-[#16213e]',
    thumbColor: 'text-[rgba(184,92,56,0.35)]',
    tag: 'E-commerce' as const,
    name: 'Moderna Móveis',
    sub: '+300% em vendas online',
    desc: 'Loja virtual completa com checkout otimizado, integração de estoque e campanhas promocionais.',
    year: '2024',
  },
  {
    num: '02',
    gradient: 'from-[#0d1b2a] to-[#1b263b]',
    thumbColor: 'text-vesk-border',
    tag: 'Sistema Web' as const,
    name: 'ClinFácil',
    sub: 'Gestão completa de clínicas',
    desc: 'Agendamento, prontuário digital, faturamento e portal do paciente em uma única plataforma.',
    year: '2024',
  },
  {
    num: '03',
    gradient: 'from-[#1a0a0a] to-[#2d0f0f]',
    thumbColor: 'text-[rgba(184,92,56,0.3)]',
    tag: 'E-commerce' as const,
    name: 'TechStore',
    sub: 'Loja integrada e escalável',
    desc: 'E-commerce B2C com múltiplos gateways, frete automatizado e painel de analytics.',
    year: '2023',
  },
  {
    num: '04',
    gradient: 'from-[#0a1a0a] to-[#0d2b0d]',
    thumbColor: 'text-vesk-border',
    tag: 'Sistema' as const,
    name: 'OrderFast',
    sub: 'Automação de pedidos',
    desc: 'Sistema de pedidos com integração ERP, filas de produção e notificações em tempo real.',
    year: '2023',
  },
  {
    num: '05',
    gradient: 'from-[#1a1520] to-[#2a1f35]',
    thumbColor: 'text-[rgba(184,92,56,0.28)]',
    tag: 'Website' as const,
    name: 'Advocacia Silva',
    sub: 'Presença digital premium',
    desc: 'Site institucional com blog, área de contato e otimização SEO para captação de leads.',
    year: '2024',
  },
  {
    num: '06',
    gradient: 'from-[#0f1a2e] to-[#1a2a4a]',
    thumbColor: 'text-vesk-border',
    tag: 'Sistema Web' as const,
    name: 'LogiTrack',
    sub: 'Rastreamento de entregas',
    desc: 'Dashboard de logística com rotas, status de entrega e integração com transportadoras.',
    year: '2023',
  },
  {
    num: '07',
    gradient: 'from-[#1e1a0f] to-[#2e2515]',
    thumbColor: 'text-[rgba(184,92,56,0.32)]',
    tag: 'E-commerce' as const,
    name: 'Casa & Jardim',
    sub: 'Marketplace de decoração',
    desc: 'Catálogo multivendor com filtros avançados, wishlist e programa de fidelidade.',
    year: '2024',
  },
  {
    num: '08',
    gradient: 'from-[#0a1520] to-[#152535]',
    thumbColor: 'text-vesk-border',
    tag: 'Sistema' as const,
    name: 'RH Pro',
    sub: 'Gestão de pessoas',
    desc: 'Folha de pagamento, ponto eletrônico, avaliações e portal do colaborador.',
    year: '2022',
  },
] as const;

export const portfolioStats = [
  { value: '50', suffix: '+', label: 'Projetos entregues' },
  { value: '12', suffix: '+', label: 'Segmentos atendidos' },
  { value: '98', suffix: '%', label: 'Taxa de satisfação', small: true },
  { value: '4', suffix: ' anos', label: 'Média de parceria' },
] as const;
